### ISSUE TITLE
Email Comment Error

### ISSUE THREAD

**Issue by jannellelegg** [omeka/plugin-Editorial#26]
We're running through a round of testing and running into an error sending comment emails. The comments are working, emails are not going through. 

Screenshot attached:
![screen shot 2016-09-20 at 10 08 40 am](https://cloud.githubusercontent.com/assets/5897725/18677812/175d3490-7f28-11e6-9d42-3df040d819ee.png)

**Comment by patrickmj** [comment]
@jannellelegg @mebrett @alyssafahringer I think this is fixed in the latest push to master. Basically, it looks like more of an issue of the UI letting you happily say 'Send Emails', but with no recipients selected (or some other way that no recipients were sent).

The UI thus does much more fancy things about selecting whom emails go to, and some automatic turning off and on of the 'Send Emails' checkbox. That's a pile of javascript, so it's worth checking across browsers for technical working. Bigger thing might be whether a whole lot of selecting and deselecting allowed users and the results in the interface make sense.

I also haven't tested this out on a page with many editorial blocks, so I'd very much appreciate help looking at the more complex situation of when there are multiple editorial block, each with different allowed users and email settings.

**Comment by jannellelegg** [comment]
@patrickmj - Great- thanks for taking a look at this! Perhaps from a UX standpoint, selecting comment participants and email recipients as one step might make this easier? 

I'll jump on the other user testing tomorrow and let you know if I have any questions about possible scenarios.

**Comment by patrickmj** [comment]
@jannellelegg thanks much! I thought a lot about the one-step vs two-step process. Easier, yes, but I think would miss real use cases. Since this is all about communications, it seems like access (which is broader than comment participant) and pinging about updates should be distinct. For example, a bunch of people should be able to look at it, but any one change to the exhibit might only be of interest to one or two people who have access, especially if it's in response to those people's thoughts. 

Kinda like how a lot of people have access to this issue's discussion, but it also makes sense for us to ping particular people with @s if we're responding to their specific comments. ;)

**Comment by jannellelegg** [comment]
Sure, that makes sense to me!
