### ISSUE TITLE
Users can edit their response comments but not delete them

### ISSUE THREAD

**Issue by mebrett** [omeka/plugin-Editorial#27]
When I reply to the original comment in an Editorial block, I can go in and edit what I wrote but there's no option for me to delete the comment.

Further, even as a SuperUser I cannot delete responses nor can I edit other people's responses.

**Comment by patrickmj** [comment]
Thanks. Full on deleting vs something else is something that I've wondered about. Since the idea is pedagogical feedback (presumably with final evaluation at the end), I wasn't sure if things should be deleted completely, losing the record, or just make it hidden somehow. So, this leads to that role playing in the testing of a teacher/student interaction. I suspect it's also a question to ask of the outside stakeholders.

That said, supers and admins should probably at least be able to edit, if not delete, responses.

**Comment by mebrett** [comment]
If we'd had this when we were working on HNM, I can see where I might have wanted to delete a comment if I realized I'd duplicated something or it was answered elsewhere, but that could also be edited to a "nevermind".

I do think it would be useful to have the outside stakeholders' feedback, since they have a better of idea of if and when it might be prudent to be able to delete comments (edit, at least at the SuperUser level, seems important)

**Comment by sheilabrennan** [comment]
Let's give supers and admins editing and deleting comment privileges for this round (if not already done). And then do our stakeholder testing.
