### ISSUE TITLE
See about a better 403 page

### ISSUE THREAD

**Issue by patrickmj** [omeka/plugin-Editorial#44]
If someone intends to give access for commenting on an Exhibit, but actually fail to do so, the result is an unpleasant 403 page. I suspect that there's not much the plugin can do about that, but worth exploring what could be more user friendly.

**Comment by zerocrates** [comment]
*IT IS FORBIDDEN*

**Comment by patrickmj** [comment]
Could I at least just show an image of an upraised middle finger?

**Comment by zerocrates** [comment]
In all seriousness something should be possible. Usually the option we take is to just hide or disable whatever button or link a user would use to get to the page if they don't have access to it. If it's an AJAX or whatever, you can tell that the response you get back is a 403 and act accordingly instead of just presenting the error page.

**Comment by patrickmj** [comment]
@zerocrates it's more likely that the link would come from an email. I could do some extra checking that emails don't go to people who haven't been access, but I suspect the possibility of bad links will still remain.
